### ISSUE TITLE
Office365 management activity API service seems mostly dysfunctional past 1 week now

### ISSUE THREAD

**Issue by vorio** [Microsoft/Office365APIEditor#1]
I am trying to integrate Office365 Activity management service with our product. Past one week, I keep getting AF50000 error for the API request to get content.

Details:
sample request type:
https://manage.office.com/api/v1.0/<<REPLACE TID>>/activity/feed/Audit/<<id>>

Response:
Internal Server Error, 500, {'error':{'code':'AF50000','message':'An internal error occurred.  Retry the request.'}}

**Comment by rykoma** [comment]
Actually, I had the same issue several weeks ago, and it was restored once.
But, I confirmed that the issue is still occurring today and I can't even start new subscriptions.
I think this is an issue of Office 365 side.

**Comment by vorio** [comment]
Looks like these are Dead APIs no one seems to be using.

**Comment by rykoma** [comment]
This API has just born, so I hope it will be improved.

**Comment by vorio** [comment]
Can we not keep this open until this is fixed. Will save others' time.

**Comment by rykoma** [comment]
If you have problems with the API itself, you should contact Microsoft support and open a support ticket.
Error code AF50000 is "internal error" of the API.

Of course  if you have problems with Office365APIEditor, feel free to post issues here.
