### ISSUE TITLE
GUI Display bugs

### ISSUE THREAD

**Issue by Bartolomeus-649** [microsoft/Office365APIEditor#10]
* The format used for displaying dates does not respect the Regional Settings in Windows.
* Sorting by _CreateDateTime_ does not work

![image](https://user-images.githubusercontent.com/7513795/69564178-d166ec00-0fb2-11ea-92a9-8f728f2e7405.png)

**Comment by rykoma** [comment]
@Bartolomeus-649,
Thank you for your feedback. I'll investigate this issue.
