### ISSUE TITLE
Internal error when use exchange api to create o365 group

### ISSUE THREAD

**Issue by 7angjinhao** [microsoft/Office365APIEditor#16]
Hi,
I get an error when i use exchange api to create o365 group,
Error: System.Exception: An internal server error occurred. The operation failed. Something went wrong and the group couldn't be created. If the problem continues, contact your email admin.
so what that message means.
Thanks

**Comment by rykoma** [comment]
It seems that it's a problem of the service side. Could you share the following information?

- Request URL / Headers / Body
- Response headers / Body
