### ISSUE TITLE
Using my own application id requires admin approval

### ISSUE THREAD

**Issue by sinag** [microsoft/Office365APIEditor#18]
Hi,

When I use your application id and click sign in with an account everything works as expected
If I put my own application id created using your instructions, than during sign-in it requires admin approval saying;

> This app may be risky. If you trust this app, please ask your admin to grant you access

Any ideas?

Regards,

**Comment by osysltd** [comment]
Hi @sinag 

Most probably you're using v2 app, switch to v1 app id and secret, grant necessary permissions once.

**Comment by sinag** [comment]
what do you you mean switching to v1?
What I did was File->New Session->Use my application button

**Comment by osysltd** [comment]
sorry I was thinking that you're using Api Editor, not Mailbox Viewer

**Comment by sinag** [comment]
Delegated permissions or application permissions?

**Comment by sinag** [comment]
To be more specific about the problem;
I have an account "xxx@yyy.com" which is from an azure active directory on a tenant and is using exchange online.
With this account, I can login with File->New Session->Sign-in
But if I try to use my own application id, which I have created with another trial personel account, than it requires admin approval from "yyy.com"

**Comment by rykoma** [comment]
@sinag 
It seems that sign-in using your app (your application ID) is detected as a risky end-user consent request.  
[https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/configure-user-consent?tabs=azure-portal#risk-based-step-up-consent](https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/configure-user-consent?tabs=azure-portal#risk-based-step-up-consent)

I could not repro the issue, and we have no way to know why your application ID is detected. Unfortunately, we can do nothing from the application side.

**Comment by sinag** [comment]
great info thanks
my application's domain is not a verified domain, my guess is this could be an issue
what about disabling risk-based step-up consent?
according to my scenario this should be done on "yyy.com" side i guess

**Comment by rykoma** [comment]
Yes. If you want to disable risk-based step-up consent, you need to do it in the tenant which the end-user belongs to.  
Though I'm not an Azure AD expert, I think disabling risk-based step-up consent is not recommended for security reasons.
