### ISSUE TITLE
Remote Sign-out

### ISSUE THREAD

**Issue by am11** [Microsoft/Office365APIEditor#2]
<ins>I understand this is required for API addition in the service, and not precisely related to API editor. Please point me which repo/team it belongs to if reasonable</ins>

Gmail offers a feature called "remote sign-out" for past 10 years: https://gmail.googleblog.com/2008/07/remote-sign-out-and-info-to-help-you.html. This is a very reasonable feature to have from the service provider from security standpoint. Do Microsoft plan to provide same feature and address dozens of folks requesting it for a long long time (google: "outlook remote sign-out")?

If/when it ever happens, could it be exposed through the Outlook.com and O365 APIs so we can consume it from out apps?

**Comment by rykoma** [comment]
If you are using the Microsoft Account, you can use Account Activity page.
https://account.live.com/Activity

Unfortunately Office 365 does not have such a feature, so please send feedback from the UserVoice page to the developer team.
https://office365.uservoice.com

**Comment by am11** [comment]
@rykoma, thanks, but https://account.live.com/Activity doesn't have explicit Remote Sign-out option. It only shows the account activity / active sessions details etc.

Apparently, the only prescribed way to exercise this (in case of lost phone, unintentionally left session active on public terminal etc.) is to change the password which invalidates the sessions. However, if we try it by signing in two different devices/browsers, change the password in one, the other one doesn't immediately signs out (it takes sometime before it invalidates the session in other places).. which is not a very option as an explicit "remote Sign-out", which Gmail, Facebook and many service providers offer.

**Comment by rykoma** [comment]
I found feedback of the same content, so I think that it would be good to vote.
https://outlook.uservoice.com/forums/284136-outlook-com/suggestions/18536800-remotley-log-out-of-other-devices

If you have questions about Microsoft Account or Office 365 Account, you should open a Microsoft support ticket.
