### ISSUE TITLE
Not able to Open .msg and .eml files from New Outlook version(1.2023.515.100 (Production)).

### ISSUE THREAD

**Issue by kapilbisht94** [microsoft/Office365APIEditor#22]
I'm not able to open any .msg and .eml files from New Outlook version(1.2023.515.100 (Production)). Although, it is working for Old Outlook.

Please review and resolve this issue.

![image](https://github.com/microsoft/Office365APIEditor/assets/68806319/af85b984-48c1-40d3-95db-0adb54079950)

**Comment by rykoma** [comment]
@kapilbisht94 
Why did you post this topic here? This repo has nothing to do with new Outlook for Windows. And, as you can see, New Outlook cannot open .msg and .eml files.
