### ISSUE TITLE
Application is not supported for this API version. 

### ISSUE THREAD

**Issue by garouds** [Microsoft/Office365APIEditor#3]
Hi.

I got this issue when trying to test your app, just after input my credentials:

Sorry, but we’re having trouble signing you in. 
We received a bad request.
Additional technical information: 
Correlation ID: f4b13198-50cd-4b72-a83f-b44173ba4421 
Timestamp: 2017-03-08 10:15:48Z 
AADSTS70001: Application '2cb57ee7-dcae-4230-a55e-085cc9e878d4' is not supported for this API version.

**Comment by garouds** [comment]
Hi.
I found the reason for this error. Looks like you HAVE to register the app in: https://apps.dev.microsoft.com NOT in the azure management portal. Totally a pain as all the references redirects to the azure portal.

**Comment by rykoma** [comment]
Thank you for your feedback.
Could you explain more detail?
If you find a wrong link, we will fix it.

**Comment by garouds** [comment]
Hi.

I worked on some tests before and other APIs only require the app to be registered in azure portal:
https://portal.azure.com or https://manage.windowsazure.com, in this case you need to register in  https://apps.dev.microsoft.com 
I overlooked this link on the description as I though azure portal was the only registration point. Looked over the web and looks like a LOT of people had same issue so it was worth mention.

Regards.

**Comment by rykoma** [comment]
Thank you for the detailed explanation.
Certainly it is hard to find out where to register the application and how to use it.
I would like to update the README and tutrial at a later date.

**Comment by cyberjoac** [comment]
+1

**Comment by rykoma** [comment]
Though it may be still a little confusing UI, I changed some UI and tutorials, and released a new build.
Any fix ideas are welcome.

**Comment by robinmalik** [comment]
I've come across this issue, when trying to follow https://github.com/cbales/report-generator. Registering an app in the Azure Portal, or at https://apps.dev.microsoft.com made no difference for me, sadly.

**Comment by rykoma** [comment]
Hello robinmalik,
Thank you for your comment.
It's hard to understand since there are many portals, many types of application, and many flow of authentication...

**Comment by rykoma** [comment]
Close this issue due to no response.
