### ISSUE TITLE
Error that manifest signing certificate in the cert store not found

### ISSUE THREAD

**Issue by joviledog** [Microsoft/Office365APIEditor#6]
I got the following error while compiling the solution file using Visual Studio 2017

Severity	Code	Description	Project	File	Line	Suppression State
Error		Unable to find manifest signing certificate in the certificate store.	Office365APIEditor			

And 3 warnings:
Severity	Code	Description	Project	File	Line	Suppression State
Warning		Unable to find code signing certificate in the current user’s Windows certificate store. To correct this, either disable signing of the ClickOnce manifest or install the certificate into the certificate store.	Office365APIEditor			
Severity	Code	Description	Project	File	Line	Suppression State
Warning		The referenced component 'System.Web.Helpers' could not be found.	Office365APIEditor			
Warning		Could not resolve this reference. Could not locate the assembly "System.Web.Helpers, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	Office365APIEditor

**Comment by rykoma** [comment]
Hello joviledog,

Could you try the following step and tell me the result please?

1. Open the property window of the project.
2. Go to [Signing] tab.
3. Check whether [Sign the ClickOnce manifests] is checked or not.
   If it is checked, uncheck it and rebuild the project.

**Comment by rykoma** [comment]
Closing due to no reply.
