### ISSUE TITLE
SmartScreen block MSI installation

### ISSUE THREAD

**Issue by Bartolomeus-649** [microsoft/Office365APIEditor#9]
When running the installation from Setup.msi Windows Defender SmartScreen displays this message:

![image](https://user-images.githubusercontent.com/7513795/69560039-61089c80-0fab-11ea-973b-5b79a149c8b9.png)

**File Details**
```
File Name: Setup.msi
File Size: 7,966,720 Bytes
Authors: Microsoft Corporation
Revision number: {4B0E6900-4642-4C35-BF7E-D1AAA57AA1EF}
Content created: 1999-06-21 09:00
MD5: 45AD43AA0BA6BF9275083FE8C66B5A57
SHA-1: AB6FB46512D7CCA87A4E20724DA46DBC17576153
SHA-256: 370D297021B4D4E2E42E0FFFE1A37BA8410672E245CF55A0D9E55DEC67E877B5
SHA-512: FAE92BE6268E07895C189DBDA5F1B094DBC3E1D8DABD59A92D3C2ADFCB43F4A3BBC79C1A3DC795FFB26EA2BDE408BC2DDB13CCB60C90DA1386BFCD4D050C4C7C
SHA3-256: 556B8291BEA030B4E37122E051CED83EFBAC50D59CBDA0879AAD601B9EEBC2FD
```

**Comment by rykoma** [comment]
Currently, this is a known limitation. MSI file is not currently signed.

https://techcommunity.microsoft.com/t5/Exchange-Team-Blog/Introducing-Office365APIEditor/ba-p/665236

> If you see a warning message from an antivirus product such as Windows Defender, be sure to read and understand any warning messages before you proceed.
